### ISSUE TITLE
Heyyy hiii , am trying to build a radio app using the assets_audio_player flutter package and am not able to play music , can u please help me ?

### ISSUE THREAD

**Issue by ampro88** [padukadafa/music_player#1]

**Comment by padukadafa** [comment]
You can read my code on the music controller in the play function. If it still doesn't work, please include the logs

**Comment by ampro88** [comment]
Am still in the beginning phase of my app bro , do u have discord or google meet ? so I can share my screen and explain ?

**Comment by padukadafa** [comment]
i have, but right now I can't bro. but u can read the documentation at https://pub.dev/packages/assets_audio_player, I think there is already documentation about live streaming radio.

**Comment by ampro88** [comment]
I am not able to understand that its soo confusing

**Comment by padukadafa** [comment]
just change the url bro. u can use Future function to apply this

```dart
final assetsAudioPlayer = AssetsAudioPlayer();

try {
    await assetsAudioPlayer.open(
        Audio.liveStream("your livestream url"),
    );
} catch (t) {
    //mp3 unreachable
} 
```
if u want to adding some audio info, just add meta
```dart
 Audio.liveStream("your url",
    metas: Metas(
            title:  "Country",
            artist: "Florent Champigny",
            album: "CountryAlbum",
            image: MetasImage.asset("assets/images/country.jpg"), //can be MetasImage.network
          ),
   );

```
